/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PractitionerIndexRouteImport } from './routes/practitioner/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as DtrIndexRouteImport } from './routes/dtr/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'
import { Route as PatientDocumentationRouteImport } from './routes/patient/documentation'
import { Route as PatientCoverageRouteImport } from './routes/patient/coverage'
import { Route as DtrLaunchRouteImport } from './routes/dtr/launch'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientAppointmentsIndexRouteImport } from './routes/patient/appointments/index'
import { Route as PatientsPatientIdOrdersRouteImport } from './routes/patients/$patientId/orders'
import { Route as PatientsPatientIdMedicationsRouteImport } from './routes/patients/$patientId/medications'
import { Route as PatientsPatientIdEncounterRouteImport } from './routes/patients/$patientId/encounter'
import { Route as PatientsPatientIdCoverageRouteImport } from './routes/patients/$patientId/coverage'
import { Route as PatientsPatientIdConditionsRouteImport } from './routes/patients/$patientId/conditions'
import { Route as PatientAppointmentsNewRouteImport } from './routes/patient/appointments/new'
import { Route as PatientAppointmentsAppointmentIdRouteImport } from './routes/patient/appointments/$appointmentId'
import { Route as PatientsPatientIdOrdersIndexRouteImport } from './routes/patients/$patientId/orders/index'
import { Route as PatientsPatientIdEncounterIndexRouteImport } from './routes/patients/$patientId/encounter/index'
import { Route as PatientsPatientIdEncounterEncounterIdRouteImport } from './routes/patients/$patientId/encounter/$encounterId'
import { Route as PatientsPatientIdOrdersOrderIdPasRouteImport } from './routes/patients/$patientId/orders/$orderId/pas'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerIndexRoute = PractitionerIndexRouteImport.update({
  id: '/practitioner/',
  path: '/practitioner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DtrIndexRoute = DtrIndexRouteImport.update({
  id: '/dtr/',
  path: '/dtr/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDocumentationRoute = PatientDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCoverageRoute = PatientCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => PatientRoute,
} as any)
const DtrLaunchRoute = DtrLaunchRouteImport.update({
  id: '/dtr/launch',
  path: '/dtr/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const PatientAppointmentsIndexRoute =
  PatientAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientsPatientIdOrdersRoute = PatientsPatientIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const PatientsPatientIdMedicationsRoute =
  PatientsPatientIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientsPatientIdEncounterRoute =
  PatientsPatientIdEncounterRouteImport.update({
    id: '/encounter',
    path: '/encounter',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientsPatientIdCoverageRoute =
  PatientsPatientIdCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientsPatientIdConditionsRoute =
  PatientsPatientIdConditionsRouteImport.update({
    id: '/conditions',
    path: '/conditions',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientAppointmentsNewRoute = PatientAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsAppointmentIdRoute =
  PatientAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientsPatientIdOrdersIndexRoute =
  PatientsPatientIdOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientsPatientIdOrdersRoute,
  } as any)
const PatientsPatientIdEncounterIndexRoute =
  PatientsPatientIdEncounterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PatientsPatientIdEncounterRoute,
  } as any)
const PatientsPatientIdEncounterEncounterIdRoute =
  PatientsPatientIdEncounterEncounterIdRouteImport.update({
    id: '/$encounterId',
    path: '/$encounterId',
    getParentRoute: () => PatientsPatientIdEncounterRoute,
  } as any)
const PatientsPatientIdOrdersOrderIdPasRoute =
  PatientsPatientIdOrdersOrderIdPasRouteImport.update({
    id: '/$orderId/pas',
    path: '/$orderId/pas',
    getParentRoute: () => PatientsPatientIdOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/dtr/launch': typeof DtrLaunchRoute
  '/patient/coverage': typeof PatientCoverageRoute
  '/patient/documentation': typeof PatientDocumentationRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/dtr/': typeof DtrIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/appointments/new': typeof PatientAppointmentsNewRoute
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/coverage': typeof PatientsPatientIdCoverageRoute
  '/patients/$patientId/encounter': typeof PatientsPatientIdEncounterRouteWithChildren
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patients/$patientId/orders': typeof PatientsPatientIdOrdersRouteWithChildren
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/encounter/$encounterId': typeof PatientsPatientIdEncounterEncounterIdRoute
  '/patients/$patientId/encounter/': typeof PatientsPatientIdEncounterIndexRoute
  '/patients/$patientId/orders/': typeof PatientsPatientIdOrdersIndexRoute
  '/patients/$patientId/orders/$orderId/pas': typeof PatientsPatientIdOrdersOrderIdPasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/dtr/launch': typeof DtrLaunchRoute
  '/patient/coverage': typeof PatientCoverageRoute
  '/patient/documentation': typeof PatientDocumentationRoute
  '/dtr': typeof DtrIndexRoute
  '/patient': typeof PatientIndexRoute
  '/practitioner': typeof PractitionerIndexRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/appointments/new': typeof PatientAppointmentsNewRoute
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/coverage': typeof PatientsPatientIdCoverageRoute
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patient/appointments': typeof PatientAppointmentsIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/encounter/$encounterId': typeof PatientsPatientIdEncounterEncounterIdRoute
  '/patients/$patientId/encounter': typeof PatientsPatientIdEncounterIndexRoute
  '/patients/$patientId/orders': typeof PatientsPatientIdOrdersIndexRoute
  '/patients/$patientId/orders/$orderId/pas': typeof PatientsPatientIdOrdersOrderIdPasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/dtr/launch': typeof DtrLaunchRoute
  '/patient/coverage': typeof PatientCoverageRoute
  '/patient/documentation': typeof PatientDocumentationRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/dtr/': typeof DtrIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/patient/appointments/$appointmentId': typeof PatientAppointmentsAppointmentIdRoute
  '/patient/appointments/new': typeof PatientAppointmentsNewRoute
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/coverage': typeof PatientsPatientIdCoverageRoute
  '/patients/$patientId/encounter': typeof PatientsPatientIdEncounterRouteWithChildren
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patients/$patientId/orders': typeof PatientsPatientIdOrdersRouteWithChildren
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/encounter/$encounterId': typeof PatientsPatientIdEncounterEncounterIdRoute
  '/patients/$patientId/encounter/': typeof PatientsPatientIdEncounterIndexRoute
  '/patients/$patientId/orders/': typeof PatientsPatientIdOrdersIndexRoute
  '/patients/$patientId/orders/$orderId/pas': typeof PatientsPatientIdOrdersOrderIdPasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/patient'
    | '/dtr/launch'
    | '/patient/coverage'
    | '/patient/documentation'
    | '/patients/$patientId'
    | '/dtr/'
    | '/patient/'
    | '/practitioner/'
    | '/patient/appointments/$appointmentId'
    | '/patient/appointments/new'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/coverage'
    | '/patients/$patientId/encounter'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/orders'
    | '/patient/appointments/'
    | '/patients/$patientId/'
    | '/patients/$patientId/encounter/$encounterId'
    | '/patients/$patientId/encounter/'
    | '/patients/$patientId/orders/'
    | '/patients/$patientId/orders/$orderId/pas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/dtr/launch'
    | '/patient/coverage'
    | '/patient/documentation'
    | '/dtr'
    | '/patient'
    | '/practitioner'
    | '/patient/appointments/$appointmentId'
    | '/patient/appointments/new'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/coverage'
    | '/patients/$patientId/medications'
    | '/patient/appointments'
    | '/patients/$patientId'
    | '/patients/$patientId/encounter/$encounterId'
    | '/patients/$patientId/encounter'
    | '/patients/$patientId/orders'
    | '/patients/$patientId/orders/$orderId/pas'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/patient'
    | '/dtr/launch'
    | '/patient/coverage'
    | '/patient/documentation'
    | '/patients/$patientId'
    | '/dtr/'
    | '/patient/'
    | '/practitioner/'
    | '/patient/appointments/$appointmentId'
    | '/patient/appointments/new'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/coverage'
    | '/patients/$patientId/encounter'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/orders'
    | '/patient/appointments/'
    | '/patients/$patientId/'
    | '/patients/$patientId/encounter/$encounterId'
    | '/patients/$patientId/encounter/'
    | '/patients/$patientId/orders/'
    | '/patients/$patientId/orders/$orderId/pas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  DtrLaunchRoute: typeof DtrLaunchRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
  DtrIndexRoute: typeof DtrIndexRoute
  PractitionerIndexRoute: typeof PractitionerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/': {
      id: '/practitioner/'
      path: '/practitioner'
      fullPath: '/practitioner/'
      preLoaderRoute: typeof PractitionerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/dtr/': {
      id: '/dtr/'
      path: '/dtr'
      fullPath: '/dtr/'
      preLoaderRoute: typeof DtrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/documentation': {
      id: '/patient/documentation'
      path: '/documentation'
      fullPath: '/patient/documentation'
      preLoaderRoute: typeof PatientDocumentationRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/coverage': {
      id: '/patient/coverage'
      path: '/coverage'
      fullPath: '/patient/coverage'
      preLoaderRoute: typeof PatientCoverageRouteImport
      parentRoute: typeof PatientRoute
    }
    '/dtr/launch': {
      id: '/dtr/launch'
      path: '/dtr/launch'
      fullPath: '/dtr/launch'
      preLoaderRoute: typeof DtrLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patient/appointments/': {
      id: '/patient/appointments/'
      path: '/appointments'
      fullPath: '/patient/appointments/'
      preLoaderRoute: typeof PatientAppointmentsIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patients/$patientId/orders': {
      id: '/patients/$patientId/orders'
      path: '/orders'
      fullPath: '/patients/$patientId/orders'
      preLoaderRoute: typeof PatientsPatientIdOrdersRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/medications': {
      id: '/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof PatientsPatientIdMedicationsRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/encounter': {
      id: '/patients/$patientId/encounter'
      path: '/encounter'
      fullPath: '/patients/$patientId/encounter'
      preLoaderRoute: typeof PatientsPatientIdEncounterRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/coverage': {
      id: '/patients/$patientId/coverage'
      path: '/coverage'
      fullPath: '/patients/$patientId/coverage'
      preLoaderRoute: typeof PatientsPatientIdCoverageRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/conditions': {
      id: '/patients/$patientId/conditions'
      path: '/conditions'
      fullPath: '/patients/$patientId/conditions'
      preLoaderRoute: typeof PatientsPatientIdConditionsRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patient/appointments/new': {
      id: '/patient/appointments/new'
      path: '/appointments/new'
      fullPath: '/patient/appointments/new'
      preLoaderRoute: typeof PatientAppointmentsNewRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments/$appointmentId': {
      id: '/patient/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/patient/appointments/$appointmentId'
      preLoaderRoute: typeof PatientAppointmentsAppointmentIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patients/$patientId/orders/': {
      id: '/patients/$patientId/orders/'
      path: '/'
      fullPath: '/patients/$patientId/orders/'
      preLoaderRoute: typeof PatientsPatientIdOrdersIndexRouteImport
      parentRoute: typeof PatientsPatientIdOrdersRoute
    }
    '/patients/$patientId/encounter/': {
      id: '/patients/$patientId/encounter/'
      path: '/'
      fullPath: '/patients/$patientId/encounter/'
      preLoaderRoute: typeof PatientsPatientIdEncounterIndexRouteImport
      parentRoute: typeof PatientsPatientIdEncounterRoute
    }
    '/patients/$patientId/encounter/$encounterId': {
      id: '/patients/$patientId/encounter/$encounterId'
      path: '/$encounterId'
      fullPath: '/patients/$patientId/encounter/$encounterId'
      preLoaderRoute: typeof PatientsPatientIdEncounterEncounterIdRouteImport
      parentRoute: typeof PatientsPatientIdEncounterRoute
    }
    '/patients/$patientId/orders/$orderId/pas': {
      id: '/patients/$patientId/orders/$orderId/pas'
      path: '/$orderId/pas'
      fullPath: '/patients/$patientId/orders/$orderId/pas'
      preLoaderRoute: typeof PatientsPatientIdOrdersOrderIdPasRouteImport
      parentRoute: typeof PatientsPatientIdOrdersRoute
    }
  }
}

interface PatientRouteChildren {
  PatientCoverageRoute: typeof PatientCoverageRoute
  PatientDocumentationRoute: typeof PatientDocumentationRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientAppointmentsAppointmentIdRoute: typeof PatientAppointmentsAppointmentIdRoute
  PatientAppointmentsNewRoute: typeof PatientAppointmentsNewRoute
  PatientAppointmentsIndexRoute: typeof PatientAppointmentsIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientCoverageRoute: PatientCoverageRoute,
  PatientDocumentationRoute: PatientDocumentationRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientAppointmentsAppointmentIdRoute: PatientAppointmentsAppointmentIdRoute,
  PatientAppointmentsNewRoute: PatientAppointmentsNewRoute,
  PatientAppointmentsIndexRoute: PatientAppointmentsIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PatientsPatientIdEncounterRouteChildren {
  PatientsPatientIdEncounterEncounterIdRoute: typeof PatientsPatientIdEncounterEncounterIdRoute
  PatientsPatientIdEncounterIndexRoute: typeof PatientsPatientIdEncounterIndexRoute
}

const PatientsPatientIdEncounterRouteChildren: PatientsPatientIdEncounterRouteChildren =
  {
    PatientsPatientIdEncounterEncounterIdRoute:
      PatientsPatientIdEncounterEncounterIdRoute,
    PatientsPatientIdEncounterIndexRoute: PatientsPatientIdEncounterIndexRoute,
  }

const PatientsPatientIdEncounterRouteWithChildren =
  PatientsPatientIdEncounterRoute._addFileChildren(
    PatientsPatientIdEncounterRouteChildren,
  )

interface PatientsPatientIdOrdersRouteChildren {
  PatientsPatientIdOrdersIndexRoute: typeof PatientsPatientIdOrdersIndexRoute
  PatientsPatientIdOrdersOrderIdPasRoute: typeof PatientsPatientIdOrdersOrderIdPasRoute
}

const PatientsPatientIdOrdersRouteChildren: PatientsPatientIdOrdersRouteChildren =
  {
    PatientsPatientIdOrdersIndexRoute: PatientsPatientIdOrdersIndexRoute,
    PatientsPatientIdOrdersOrderIdPasRoute:
      PatientsPatientIdOrdersOrderIdPasRoute,
  }

const PatientsPatientIdOrdersRouteWithChildren =
  PatientsPatientIdOrdersRoute._addFileChildren(
    PatientsPatientIdOrdersRouteChildren,
  )

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdConditionsRoute: typeof PatientsPatientIdConditionsRoute
  PatientsPatientIdCoverageRoute: typeof PatientsPatientIdCoverageRoute
  PatientsPatientIdEncounterRoute: typeof PatientsPatientIdEncounterRouteWithChildren
  PatientsPatientIdMedicationsRoute: typeof PatientsPatientIdMedicationsRoute
  PatientsPatientIdOrdersRoute: typeof PatientsPatientIdOrdersRouteWithChildren
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdConditionsRoute: PatientsPatientIdConditionsRoute,
  PatientsPatientIdCoverageRoute: PatientsPatientIdCoverageRoute,
  PatientsPatientIdEncounterRoute: PatientsPatientIdEncounterRouteWithChildren,
  PatientsPatientIdMedicationsRoute: PatientsPatientIdMedicationsRoute,
  PatientsPatientIdOrdersRoute: PatientsPatientIdOrdersRouteWithChildren,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  DtrLaunchRoute: DtrLaunchRoute,
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
  DtrIndexRoute: DtrIndexRoute,
  PractitionerIndexRoute: PractitionerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
