/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdMedicationsRouteImport } from './routes/patients/$patientId/medications'
import { Route as PatientsPatientIdConditionsRouteImport } from './routes/patients/$patientId/conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const PatientsPatientIdMedicationsRoute =
  PatientsPatientIdMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientsPatientIdConditionsRoute =
  PatientsPatientIdConditionsRouteImport.update({
    id: '/conditions',
    path: '/conditions',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/$patientId/conditions': typeof PatientsPatientIdConditionsRoute
  '/patients/$patientId/medications': typeof PatientsPatientIdMedicationsRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/$patientId'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/medications'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/patients/$patientId'
    | '/patients/$patientId/conditions'
    | '/patients/$patientId/medications'
    | '/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/medications': {
      id: '/patients/$patientId/medications'
      path: '/medications'
      fullPath: '/patients/$patientId/medications'
      preLoaderRoute: typeof PatientsPatientIdMedicationsRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/conditions': {
      id: '/patients/$patientId/conditions'
      path: '/conditions'
      fullPath: '/patients/$patientId/conditions'
      preLoaderRoute: typeof PatientsPatientIdConditionsRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
  }
}

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdConditionsRoute: typeof PatientsPatientIdConditionsRoute
  PatientsPatientIdMedicationsRoute: typeof PatientsPatientIdMedicationsRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdConditionsRoute: PatientsPatientIdConditionsRoute,
  PatientsPatientIdMedicationsRoute: PatientsPatientIdMedicationsRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
